document/urls.py
from django.urls import path
from . import views
from .views import DocumentCreate

# Все адреса веб-сервиса для работы с документом
urlpatterns = [
    # path(То что вставляется после \, То, что вызывается в данном случае, Название данного перенаправления)
    path('upload', DocumentCreate.as_view(), name='documents'), # загрузка документа на сервер
    path('download', views.download), # выгрузка документа
    path('view', views.ViewDocument), # просмотр документа
    path('viewAndCreate', views.ViewDocumentAndCreateDocument), # просмотр документа
    path('createDocumentsMultiple', views.CreateDocumentMultiple), # просмотр документа
    path('update', views.UpdateDocument), # обновление документа
    path('new', views.create_New_Document, name='newdocuments'), # создание нового документа
    # path('savedelement/delete', views.DeleteSavedElement), # удаление сохранённого элемента
    # path('savedelement/create', views.SaveSavedElement), # создание сохранённого элемента
    path('variable/delete', views.DeleteVariable), # удаление переменной
    path('variable/create', views.SaveVariable), # создание переменной
    path('delete', views.DeleteDocument), # удаление документа
    # path('save_image', views.SaveCover), # сохранение обложки
    path('save_doc_image', views.SaveImage), # сохранение картинки
    path('document_add', views.AddDocumentToUser), # копирование документа
    path('document_copy', views.CopyDocument), # копирование документа
    path('doctype_add', views.CreateDocType), # добавление типа документа
    path('doctype_remove', views.DeleteDocType), # удаление типа документа
    path('acceptFilters', views.AcceptFilters),
    path('connect_objects_to_document/<int:pk>/', views.connect_objects_to_document, name='connect_objects_to_document'),
    path('delete_object_from_document/<int:pk>/', views.delete_object_from_document, name='delete_object_from_document'),
]

main/urls.py
from django.urls import path
from . import views

# Все адреса веб-сервиса
urlpatterns = [
    # path(То что вставляется после \, То, что вызывается в данном случае, Название данного перенаправления)
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    path('match_machine', views.match_machine, name='match_machine'),
]

taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('document/', include('document.urls')),
    path('accounts/', include('user_manager.urls')),
    path('database/', include('database_manager.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

document/models.py
from django.db import models
from django.contrib.auth.models import User
from user_manager.models import Profile, Organisation
from database_manager.models import Object


def user_directory_path(instance, filename):
    return f'documents/user_{instance.user.id}/{filename}'


class DocType(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(verbose_name='Название', max_length=100, null=True, blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Тип документа'
        verbose_name_plural = 'Типы документов'


# Класс документы для базы данных
class DocumentsPattern(models.Model):
    name = models.CharField(verbose_name='Название', max_length=100, null=True, blank=True)
    type = models.ForeignKey(DocType, on_delete=models.CASCADE, default=1, null=True, blank=True)
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    file = models.FileField(upload_to=user_directory_path, null=True, blank=True)
    json = models.JSONField(verbose_name='JSON строка', default=dict, null=True, blank=True)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    documentOfOrganisation = models.BooleanField(default=False, null=True, blank=True)
    picture = models.ImageField(null=True, blank=True, upload_to=user_directory_path)
    lastUpdate = models.DateTimeField(auto_now=True, null=True, blank=True)
    dateCreate = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    downloadsTimes = models.PositiveIntegerField(default=0,null=True, blank=True)
    

    def __str__(self):
        return f"{self.name} от {self.owner}"

    def save(self, *args, **kwargs):
        try:
            super().save(*args, **kwargs)  # Call the "real" save() method.
            return True
        except:
            return False

    def print_lastUpdate_in_other_format(self):
        return self.lastUpdate.strftime('%d.%m.%Y')

    class Meta:
        verbose_name = 'Документ'
        verbose_name_plural = 'Документы'



#TO DO Убрать как ненужное
class VariableBlock(models.Model):
    name = models.CharField(verbose_name='Название', max_length=100, null=True, blank=True)
    meaning = models.TextField(verbose_name='Значение', null=True, blank=True)
    
    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Переменная'
        verbose_name_plural = 'Переменные'
        
    
class Document_VariableBlock(models.Model):
    document = models.ForeignKey(DocumentsPattern, on_delete=models.CASCADE, null=True, blank=True)
    variable = models.ForeignKey(VariableBlock, on_delete=models.CASCADE, null=True, blank=True)


class Fonts(models.Model):
    name = models.CharField(verbose_name='Название', max_length=100, null=True, blank=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Шрифт'
        verbose_name_plural = 'Шрифты'


class SavedElements(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(verbose_name='Название', max_length=100, null=True, blank=True)
    type = models.ForeignKey(DocType, on_delete=models.CASCADE, default=1, null=True, blank=True)
    json = models.JSONField(verbose_name='JSON строка', null=True, blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Сохраненный элемент'
        verbose_name_plural = 'Сохраненные элементы'


class Document_ParentDocument(models.Model):
    document = models.ForeignKey(DocumentsPattern, on_delete=models.CASCADE, null=True, blank=True, related_name='document')
    parent = models.ForeignKey(DocumentsPattern, on_delete=models.CASCADE, null=True, blank=True, related_name='parent_document')
    parentDocumentChanged = models.BooleanField(default=False, null=True, blank=True)
    userRequested = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)


class GroupOfDocument(models.Model):
    name = models.CharField(verbose_name='Название группы', max_length=100, null=True, blank=True)


class CreatedDocument(models.Model):
    name = models.CharField(verbose_name='Название документа', max_length=100, null=True, blank=True)
    groupofdocument = models.ForeignKey(GroupOfDocument, on_delete=models.CASCADE, null=True, blank=True)
    file = models.FileField(upload_to=user_directory_path, null=True, blank=True)
    json = models.JSONField('JSON строка', default=dict, null=True, blank=True)
    pattern = models.ForeignKey(DocumentsPattern, on_delete=models.CASCADE, null=True, blank=True)
    lastUpdate = models.DateTimeField(auto_now=True, null=True, blank=True)
    dateCreate = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    downloadsTimes = models.PositiveIntegerField(default=0,null=True, blank=True)
    
class DocumentPattern_Objects(models.Model):
    document = models.ForeignKey(DocumentsPattern, on_delete=models.CASCADE, null=True, blank=True, related_name='object_document')
    object = models.ForeignKey(Object, on_delete=models.CASCADE, null=True, blank=True, related_name='document_object')
    

document/forms.py
from .models import DocumentsPattern, DocType
from django import forms


class DocumentForm(forms.ModelForm):
    class Meta:
        model = DocumentsPattern
        fields = ["name", "owner", "description", "file", "type", "documentOfOrganisation"]
        doctypes = forms.ModelChoiceField(queryset=DocType.objects.all(), empty_label=None, to_field_name="type")
        
        widgets = {
            "name": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название',
                'value': "Документ1",
            }),
            "owner": forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Введите автора',
            }),
            "description": forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите описание',
                'required': False,
            }),
            "file": forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'name': 'myfile1',
                'type': 'file',
                'id': 'inputFile',
            }),
            "documentOfOrganisation": forms.CheckboxInput()
        }

templates/document/document_create.html
{% extends 'base.html' %}

{% block title %}
    Загрузка документа
{% endblock %}

{% block connection %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main/create_document.css' %}">
{% endblock %}

{% block content %}
<div class="modal fade" id="typeModal" tabindex="-1" aria-labelledby="typeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="typeModalLabel">Добавить тип документов</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
        </div>
        <div class="modal-body">
            <label for="type_name">Название для типа данных:</label>
            <input id="type_name">
        </div>
        <div class="modal-footer">
            <button onclick="SaveType();">Добавить</button>
        </div>
      </div>
    </div>
  </div>
<div class="main">
<h1>{{ title }}</h1>
<div class="form_control">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="{{ form.name.id_for_label }}">Название:</label>
        {{ form.name }}
    </div>
    <div class="fieldWrapper">
        {{ form.type.errors }}
        <label for="{{ form.type.id_for_label }}">Тип документа:</label>
        <div class="type_div">
            {{ form.type }}
            <a class="btn btn-labeled" onclick="BtnAddType(event);"><i class="fas fa-plus" style="color: green;"></i></a>
            <a class="btn btn-labeled" onclick="BtnRemoveType(event);"><i class="fas fa-xmark" style="color: red;"></i></a>
        </div>
    </div>
    {% if profile.canAddOrganisationDocument %}
    <div class="fieldWrapper">
        {{ form.documentOfOrganisation.errors }}
        <label for="{{ form.documentOfOrganisation.id_for_label }}">Документ для организации:</label>
        {{ form.documentOfOrganisation }}
    </div>
    {% endif %}
    <div class="fieldWrapper">
        {{ form.description.errors }}
        <label for="{{ form.description.id_for_label }}">Описание:</label>
        {{ form.description }}
    </div>
    <div class="fieldWrapper">
        {{ form.file.errors }}
        <label for="{{ form.file.id_for_label }}">Файл:</label>
        {{ form.file }}
    </div>
    <button type="submit" class="btn btn-success">Создать</button>
</form>
</div>
</div>
{% endblock %}

{% block script %}
    <script lang="JavaScript">

        function BtnAddType(evt){
            document.querySelector('#type_name').value = "";
            typeModal.toggle();
        }

        function BtnRemoveType(){
            if (document.querySelector('#id_type').value == 1){
                alert('Вы не можете удалить этот тип')
                return;
            }
            $.ajax({
                type: "POST",
                url: "/document/doctype_remove",
                data: JSON.stringify({id: document.querySelector('#id_type').value}),
                contentType: "application/json; charset=utf-8",
                success: function(res, status, xhr){
                    switch (xhr.status){
                        case 200:
                            var option = document.querySelector('option[value="'+ document.querySelector('#id_type').value +'"]');
                            document.querySelector('#id_type').removeChild(option);
                            break;
                        case 304:
                            break;
                    }
                } 
            });
        }


        function SaveType(){
            $.ajax({
                type: "POST",
                url: "/document/doctype_add",
                data: JSON.stringify({name: document.querySelector('#type_name').value}),
                contentType: "application/json; charset=utf-8",
                success: function(res, status, xhr){
                    switch (xhr.status){
                        case 200:
                            var option = document.createElement('option');
                            option.value = xhr.getResponseHeader('id'); 
                            option.textContent = document.querySelector('#type_name').value;
                            document.querySelector('#id_type').appendChild(option);
                            typeModal.toggle();
                            document.querySelector('#id_type').value = xhr.getResponseHeader('id')
                            break;
                        case 304:
                            break;
                    }
                } 
            });
        }

        document.getElementById("inputFile").onchange = function(){
            elem = document.getElementById("inputFile");
            splitted = elem.value.split('\\');
            document.getElementById("id_name").value = splitted[splitted.length - 1].split('.')[0];
        }

        var typeModal = new bootstrap.Modal(document.getElementById('typeModal'), {
            keyboard: false
        })
    </script>
{% endblock %}

templates/document/new_document.html
{% extends 'base.html' %}

{% block title %}
    Создание шаблона
{% endblock %}

{% block connection %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main/create_document.css' %}">
{% endblock %}

{% block content %}
<div class="modal fade" id="typeModal" tabindex="-1" aria-labelledby="typeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="typeModalLabel">Добавить тип документов</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
        </div>
        <div class="modal-body">
            <label for="type_name">Название для типа документа:</label>
            <input id="type_name">
        </div>
        <div class="modal-footer">
            <button onclick="SaveType();">Добавить</button>
        </div>
      </div>
    </div>
  </div>
<div class="main">
<h1>{{ title }}</h1>
<div class="form_control">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="{{ form.name.id_for_label }}">Название:</label>
        {{ form.name }}
    </div>
    <div class="fieldWrapper">
        {{ form.type.errors }}
        <label for="{{ form.type.id_for_label }}">Тип документа:</label>
        <div class="type_div">
            {{ form.type }}
            <a class="btn btn-labeled" onclick="BtnAddType(event);"><i class="fas fa-plus" style="color: green;"></i></a>
            <a class="btn btn-labeled" onclick="BtnRemoveType(event);"><i class="fas fa-xmark" style="color: red;"></i></a>
        </div>
    </div>
    {% if profile.canAddOrganisationDocument %}
    <div class="fieldWrapper invisible">
        {{ form.documentOfOrganisation.errors }}
        <label for="{{ form.documentOfOrganisation.id_for_label }}">Документ для организации:</label>
        {{ form.documentOfOrganisation }}
    </div>
    {% endif %}
    <div class="fieldWrapper invisible">
        {{ form.description.errors }}
        <label for="{{ form.description.id_for_label }}">Описание:</label>
        {{ form.description }}
    </div>
    <button type="submit" class="btn btn-success">Создать</button>
</form>
</div>
</div>
{% endblock %}

{% block script %}
    <script lang="JavaScript">

        function BtnAddType(evt){
            document.querySelector('#type_name').value = "";
            typeModal.toggle();
        }

        function BtnRemoveType(){
            if (document.querySelector('#id_type').value == 1){
                alert('Вы не можете удалить этот тип')
                return;
            }
            $.ajax({
                type: "POST",
                url: "/document/doctype_remove",
                data: JSON.stringify({id: document.querySelector('#id_type').value}),
                contentType: "application/json; charset=utf-8",
                success: function(res, status, xhr){
                    switch (xhr.status){
                        case 200:
                            var option = document.querySelector('option[value="'+ document.querySelector('#id_type').value +'"]');
                            document.querySelector('#id_type').removeChild(option);
                            break;
                        case 304:
                            break;
                    }
                } 
            });
        }


        function SaveType(){
            $.ajax({
                type: "POST",
                url: "/document/doctype_add",
                data: JSON.stringify({name: document.querySelector('#type_name').value}),
                contentType: "application/json; charset=utf-8",
                success: function(res, status, xhr){
                    switch (xhr.status){
                        case 200:
                            var option = document.createElement('option');
                            option.value = xhr.getResponseHeader('id'); 
                            option.textContent = document.querySelector('#type_name').value;
                            document.querySelector('#id_type').appendChild(option);
                            typeModal.toggle();
                            document.querySelector('#id_type').value = xhr.getResponseHeader('id')
                            break;
                        case 304:
                            break;
                    }
                } 
            });
        }

        var typeModal = new bootstrap.Modal(document.getElementById('typeModal'), {
            keyboard: false
        })
    </script>
{% endblock %}